#!/usr/bin/env python3
"""Compile Catalog/models.json into Sources/Model/GUSModelCatalog.generated.swift.

Only entries with status "pinned" reach the app. A pinned entry must carry a
full provenance pin (revision, filename, byte_count, sha256, license) and its
download URL is always derived as https://huggingface.co/<repo>/resolve/<rev>/<file>,
so the catalog cannot smuggle in another host.

  python3 scripts/gus_catalog/generate.py          # write the Swift file
  python3 scripts/gus_catalog/generate.py --check  # fail if it is stale (CI)
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.parse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CATALOG = ROOT / "Catalog" / "models.json"
OUTPUT = ROOT / "Sources" / "Model" / "GUSModelCatalog.generated.swift"

REQUIRED = ("id", "swift_name", "name", "family", "vendor", "parameters", "repository",
            "filename", "revision", "byte_count", "sha256", "license_name", "license_url",
            "commercial_use", "attribution", "chat_template", "experimental")
STATUSES = {"pinned", "candidate", "rejected"}
EVIDENCE = {"unmeasured", "desktop-smoke", "device-measured"}
# Builtin llama.cpp template names accepted as overrides (llama_chat_apply_template).
TEMPLATES = {"auto", "chatml", "llama2", "llama3", "llama4", "phi3", "phi4", "gemma", "mistral-v7",
             "granite", "deepseek3", "command-r", "zephyr", "vicuna", "exaone3", "smolvlm",
             "megrez", "yandex", "bailing", "gigachat", "openchat", "orion", "monarch", "rwkv-world"}


class CatalogError(ValueError):
    pass


def _swift_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _swift_int(value: int) -> str:
    s = str(value)
    groups = []
    while len(s) > 3:
        groups.insert(0, s[-3:])
        s = s[:-3]
    return "_".join([s] + groups)


def validate(catalog: dict) -> list[dict]:
    if catalog.get("schema") != 1:
        raise CatalogError("unsupported catalog schema")
    seen_ids, seen_names, pinned = set(), set(), []
    for e in catalog["models"]:
        mid = e.get("id", "?")
        if not re.fullmatch(r"[a-z0-9][a-z0-9-]{2,63}", mid):
            raise CatalogError(f"{mid}: invalid id")
        if mid in seen_ids:
            raise CatalogError(f"{mid}: duplicate id")
        seen_ids.add(mid)
        if e.get("status") not in STATUSES:
            raise CatalogError(f"{mid}: status must be one of {sorted(STATUSES)}")
        if not re.fullmatch(r"[A-Za-z0-9._-]+/[A-Za-z0-9._-]+", e.get("repository", "")):
            raise CatalogError(f"{mid}: repository must be owner/name")
        if e["status"] != "pinned":
            continue
        missing = [k for k in REQUIRED if k not in e]
        if missing:
            raise CatalogError(f"{mid}: pinned entry missing {missing}")
        if not re.fullmatch(r"[a-z][A-Za-z0-9]*", e["swift_name"]) or e["swift_name"] in seen_names:
            raise CatalogError(f"{mid}: invalid or duplicate swift_name")
        seen_names.add(e["swift_name"])
        if not re.fullmatch(r"[0-9a-f]{40}", e["revision"]):
            raise CatalogError(f"{mid}: revision must be a full commit sha")
        if not re.fullmatch(r"[0-9a-f]{64}", e["sha256"]):
            raise CatalogError(f"{mid}: sha256 must be 64 lowercase hex chars")
        if not (isinstance(e["byte_count"], int) and e["byte_count"] > 0):
            raise CatalogError(f"{mid}: byte_count must be a positive integer")
        if "/" in e["filename"] or not e["filename"].lower().endswith(".gguf"):
            raise CatalogError(f"{mid}: filename must be a top-level .gguf")
        if not e["license_url"].startswith("https://"):
            raise CatalogError(f"{mid}: license_url must be https")
        if e["chat_template"] not in TEMPLATES:
            raise CatalogError(f"{mid}: unknown chat_template {e['chat_template']!r}")
        if e.get("evidence", "unmeasured") not in EVIDENCE:
            raise CatalogError(f"{mid}: evidence must be one of {sorted(EVIDENCE)}")
        if e.get("gated"):
            raise CatalogError(f"{mid}: gated repositories cannot be downloaded anonymously")
        for k in ("kv_bytes_per_token", "context_length"):
            if k in e and not (isinstance(e[k], int) and e[k] > 0):
                raise CatalogError(f"{mid}: {k} must be a positive integer")
        pinned.append(e)
    if not pinned:
        raise CatalogError("catalog has no pinned models")
    return pinned


def source_url(e: dict) -> str:
    return (f"https://huggingface.co/{e['repository']}/resolve/{e['revision']}/"
            f"{urllib.parse.quote(e['filename'])}")


def render(pinned: list[dict]) -> str:
    out = [
        "// GENERATED by scripts/gus_catalog/generate.py from Catalog/models.json. Do not edit.",
        "import Foundation",
        "",
        "extension GUSModelManifest {",
    ]
    for e in pinned:
        opt_int = lambda k: _swift_int(e[k]) if k in e else "nil"  # noqa: E731
        opt_str = lambda k: _swift_string(e[k]) if e.get(k) else "nil"  # noqa: E731
        tmpl = "nil" if e["chat_template"] == "auto" else _swift_string(e["chat_template"])
        out += [
            f"    public static let {e['swift_name']} = GUSModelManifest(",
            f"        id: {_swift_string(e['id'])},",
            f"        modelName: {_swift_string(e['name'])},",
            f"        repository: {_swift_string(e['repository'])},",
            f"        filename: {_swift_string(e['filename'])},",
            f"        revision: {_swift_string(e['revision'])},",
            f"        sourceURL: URL(string: {_swift_string(source_url(e))})!,",
            f"        byteCount: {_swift_int(e['byte_count'])},",
            f"        sha256: {_swift_string(e['sha256'])},",
            f"        licenseName: {_swift_string(e['license_name'])},",
            f"        licenseURL: URL(string: {_swift_string(e['license_url'])})!,",
            f"        attribution: {_swift_string(e['attribution'])},",
            f"        family: {_swift_string(e['family'])},",
            f"        vendor: {_swift_string(e['vendor'])},",
            f"        parameterLabel: {_swift_string(e['parameters'])},",
            f"        commercialUse: {'true' if e['commercial_use'] else 'false'},",
            f"        chatTemplateOverride: {tmpl},",
            f"        isExperimental: {'true' if e['experimental'] else 'false'},",
            f"        evidence: .{_evidence_case(e.get('evidence', 'unmeasured'))},",
            f"        architecture: {opt_str('architecture')},",
            f"        kvBytesPerToken: {opt_int('kv_bytes_per_token')},",
            f"        nativeContextLength: {opt_int('context_length')}",
            "    )",
            "",
        ]
    names = ", ".join(e["swift_name"] for e in pinned)
    out += [
        "    /// Every artifact the app may download, in catalog order.",
        f"    public static let all: [GUSModelManifest] = [{names}]",
        "}",
        "",
    ]
    return "\n".join(out)


def _evidence_case(value: str) -> str:
    head, *rest = value.split("-")
    return head + "".join(p.capitalize() for p in rest)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--catalog", type=Path, default=CATALOG)
    ap.add_argument("--output", type=Path, default=OUTPUT)
    ap.add_argument("--check", action="store_true", help="fail if the generated file is stale")
    args = ap.parse_args(argv)
    try:
        pinned = validate(json.loads(args.catalog.read_text(encoding="utf-8")))
    except CatalogError as e:
        print(f"catalog error: {e}", file=sys.stderr)
        return 1
    text = render(pinned)
    if args.check:
        current = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if current != text:
            print(f"{args.output} is stale; run scripts/gus_catalog/generate.py", file=sys.stderr)
            return 1
        print(f"catalog OK: {len(pinned)} pinned models")
        return 0
    args.output.write_text(text, encoding="utf-8")
    print(f"wrote {args.output} ({len(pinned)} pinned models)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
